/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testcrud;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author Ahmad Dimas Abid M
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        alert = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtNIS = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        rbL = new javax.swing.JRadioButton();
        rbP = new javax.swing.JRadioButton();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSmp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Tanggal = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM MALANG");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 0, 680, 40);

        jLabel2.setFont(new java.awt.Font("NewsGoth BT", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("T h e  R e a l  I n f o r m a t i c  S c h o o l s");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 40, 260, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 910, 80);

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(null);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(0, 28, 250, 2);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel3.setText("ISIAN DATA SISWA");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 0, 150, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel4.setText("Tgl Lahir");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 160, 70, 20);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 200, 170, 20);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel6.setText("Kelas");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 250, 100, 20);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel7.setText("Alamat");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 430, 150, 20);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel9.setText("NIS");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 30, 60, 20);
        jPanel3.add(txtNama);
        txtNama.setBounds(10, 110, 220, 30);
        jPanel3.add(txtKelas);
        txtKelas.setBounds(10, 270, 220, 30);
        jPanel3.add(txtNIS);
        txtNIS.setBounds(10, 50, 220, 30);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 450, 220, 96);

        btnGroup.add(rbL);
        rbL.setText("Laki - Laki");
        jPanel3.add(rbL);
        rbL.setBounds(10, 220, 100, 23);

        btnGroup.add(rbP);
        rbP.setText("Perempuan");
        jPanel3.add(rbP);
        rbP.setBounds(130, 220, 100, 23);
        jPanel3.add(txtEmail);
        txtEmail.setBounds(10, 330, 220, 30);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel10.setText("Email");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 310, 100, 20);
        jPanel3.add(txtTelp);
        txtTelp.setBounds(10, 570, 220, 30);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel11.setText("Nomor Telepon");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 550, 130, 20);
        jPanel3.add(txtSmp);
        txtSmp.setBounds(10, 390, 220, 30);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel12.setText("Asal SMP");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 370, 100, 20);
        jPanel3.add(Tanggal);
        Tanggal.setBounds(80, 160, 150, 30);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        jLabel8.setText("NAMA");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 90, 140, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 80, 250, 610);

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(540, 10, 80, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(290, 10, 80, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(420, 10, 80, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(20, 10, 80, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(150, 10, 80, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(270, 90, 640, 50);

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));
        jPanel5.setLayout(null);

        tblData.setBackground(new java.awt.Color(255, 255, 204));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Tanggal Lahir", "Jenis Kelamin", "Kelas", "Email", "Asal SMP", "Alamat", "No Telepon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 620, 520);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(270, 150, 640, 540);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 910, 690);

        setSize(new java.awt.Dimension(930, 733));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String jk = "";
        if (rbL.isSelected()) jk = "L";
        if (rbP.isSelected()) jk = "P";
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());

        if(txtNIS.getText().equals("") || txtNama.getText().equals("") || tanggal.equals("") || jk.equals("") ||
                txtKelas.getText().equals("") || txtEmail.getText().equals("") || txtSmp.getText().equals("") ||
                txtAlamat.getText().equals("") || txtTelp.getText().equals("")){
            alert.showMessageDialog(this, "Harap Lengkapi Data", "Error", alert.WARNING_MESSAGE);
        } else {
            String sql = "INSERT INTO t_siswa VALUES ('"+txtNIS.getText()+"', '"+txtNama.getText()
                    +"', '"+tanggal+"', '"+jk+"', '"+txtKelas.getText()+"', '"+txtEmail.getText()
                    +"', '"+txtSmp.getText()+"', '"+txtAlamat.getText()+"', '"+txtTelp.getText()+"')";
            int status = KoneksiDB.execute(sql);
            if(status == 1){
                alert.showMessageDialog(this, "Data Berhasil Ditambahkan", "SUKSES", alert.INFORMATION_MESSAGE);
                selectData();
            } else {
                alert.showMessageDialog(this, "Data Gagal Ditambahkan", "GAGAL", alert.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            String nis = tblData.getValueAt(baris, 0).toString();
            String sql = "DELETE FROM t_siswa WHERE NIS='"+nis+"'";
            int status = KoneksiDB.execute(sql);
            if(status == 1){
                alert.showMessageDialog(this, "Data Berhasil Dihapus", "SUKSES", alert.INFORMATION_MESSAGE);
                selectData();
            } else {
                alert.showMessageDialog(this, "Data Gagal Dihapus", "GAGAL", alert.WARNING_MESSAGE);
            }
        } else {
            alert.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu!", "Error", alert.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtNIS.setText("");
        txtNama.setText("");
        Tanggal.setDate(null);
        txtKelas.setText("");
        txtEmail.setText("");
        txtSmp.setText("");
        txtAlamat.setText("");
        txtTelp.setText("");
        btnGroup.clearSelection();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        selectData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String jk = "";
        if (rbL.isSelected()) jk = "L";
        if (rbP.isSelected()) jk = "P";

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());

        if(txtNIS.getText().equals("") || txtNama.getText().equals("") || tanggal.equals("") || jk.equals("") ||
                txtKelas.getText().equals("") || txtEmail.getText().equals("") || txtSmp.getText().equals("") ||
                txtAlamat.getText().equals("") || txtTelp.getText().equals("")){
            alert.showMessageDialog(this, "Harap Lengkapi Data", "Error", alert.WARNING_MESSAGE);
        } else {
            String sql = "UPDATE t_siswa SET "
                    + "NamaSiswa='"+txtNama.getText()+"', "
                    + "Tgl_Lahir='"+tanggal+"', "
                    + "JenisKelamin='"+jk+"', "
                    + "Kelas='"+txtKelas.getText()+"', "
                    + "Email='"+txtEmail.getText()+"', "
                    + "Asal_SMP='"+txtSmp.getText()+"', "
                    + "Alamat='"+txtAlamat.getText()+"', "
                    + "No_Telp='"+txtTelp.getText()+"' WHERE NIS='"+txtNIS.getText()+"'";
            int status = KoneksiDB.execute(sql);
            if(status == 1){
                alert.showMessageDialog(this, "Data Berhasil Diupdate", "SUKSES", alert.INFORMATION_MESSAGE);
                selectData();
            } else {
                alert.showMessageDialog(this, "Data Gagal Diupdate", "GAGAL", alert.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            txtNIS.setText(tblData.getValueAt(baris, 0).toString());
            txtNama.setText((String) tblData.getValueAt(baris, 1));
            
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try {
                dateFormat = date.parse(tblData.getValueAt(baris, 2).toString());
            } catch (ParseException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Tanggal.setDate(dateFormat);
            String jk = tblData.getValueAt(baris, 3).toString();
            if(jk.equals("Laki - Laki"))
                rbL.setSelected(true);
            else 
                rbP.setSelected(true);
            txtKelas.setText(tblData.getValueAt(baris, 4).toString());
            txtEmail.setText(tblData.getValueAt(baris, 5).toString());
            txtSmp.setText(tblData.getValueAt(baris, 6).toString());
            txtAlamat.setText(tblData.getValueAt(baris, 7).toString());
            txtTelp.setText(tblData.getValueAt(baris, 8).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void selectData() {
        String kolom[] = {"NIS", "Nama Siswa", "Tanggal Lahir", "Jenis Kelamin", "Kelas", "Email", "Asal SMP", "Alamat", "No Telp"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String sql = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(sql);
        try{
            while(rs.next()){
                String nis = rs.getString(1);
                String nama = rs.getString(2);
                String tgl = rs.getString(3);
                String jk = "";
                if(rs.getString(4).equals("L")) jk = "Laki - Laki";
                else jk = "Perempuan";
                String kelas = rs.getString(5);
                String email = rs.getString(6);
                String smp = rs.getString(7);
                String alamat = rs.getString(8);
                String telp = rs.getString(9);
                String data[] = {nis, nama, tgl, jk, kelas, email, smp, alamat, telp};
                dtm.addRow(data);
            }
        } catch (SQLException e){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, e);
        }
        tblData.setModel(dtm);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JOptionPane alert;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbL;
    private javax.swing.JRadioButton rbP;
    private javax.swing.JTable tblData;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNIS;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSmp;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables

    
}
